publishDir = "public"
canonifyurls = true
baseURL = "https://mekann2904.github.io/mekann/"
languageCode = "jp"
title = "Mekann's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitalk = true
enableSearch = true

[params]
  author = "Mekann"
  github = "Mekann2904"
  twitter = "Mekann2904"
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  avatar = "/images/avatar.jpg"
  headerIcon = "/images/github-mark-white.png"
  location = "Japan"
#  enableGitalk = true
#  enableSearch = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[outputs]
  home = ["html", "json"]  # RSSを停止し、JSON出力を追加

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

[params.gitalk]
  clientID = "Your client ID"
  clientSecret = "Your client secret"
  repo = "repo"
  owner = "Your Github username"
  admin = "Your Github username"
  id = "location.pathname"
  labels = "gitalk"
  perPage = 30
  pagerDirection = "last"
  createIssueManually = true
  distractionFreeMode = false

