import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import { clearPromptProvidersForTests, hashFragment, registerPromptProvider, renderPromptFragments } from "../prompt-core/index.js";
vi.mock("@earendil-works/pi-coding-agent", () => ({}));
function mockPi() { const hooks = new Map<string, Function>(); return { hooks, events: { emit: vi.fn() }, on: vi.fn((e: string, h: Function) => hooks.set(e, h)) }; }
const frag = (id: string, stability: any, content: string) => ({ id, source: "test", kind: "coding_guidelines" as const, stability, scope: "global" as const, priority: 1, version: "v1", content });
describe("cache-friendly-prompt", () => {
  let dir: string;
  beforeEach(() => { clearPromptProvidersForTests(); dir = fs.mkdtempSync(path.join(os.tmpdir(), "cfp-")); });
  afterEach(() => clearPromptProvidersForTests());
  async function load(pi: any, config?: any) { const { default: ext } = await import("./index.js"); ext(pi, config); }
  it("registers hooks", async () => { const pi = mockPi(); await load(pi); expect([...pi.hooks.keys()]).toEqual(["before_agent_start", "context", "before_provider_request", "message_end"]); });
  it("before_agent_start appends stable then semi-stable but not dynamic", async () => { registerPromptProvider({ id: "p", getFragments: () => [frag("s", "stable", "stable text"), frag("m", "semi_stable", "semi text"), frag("d", "dynamic", "dynamic text")] }); const pi = mockPi(); await load(pi); const r = await pi.hooks.get("before_agent_start")!({ systemPrompt: "BASE" }, { cwd: dir, model: { provider: "p", id: "m" } }); expect(r.systemPrompt).toMatch(/^BASE/); expect(r.systemPrompt.indexOf("stable text")).toBeLessThan(r.systemPrompt.indexOf("semi text")); expect(r.systemPrompt).not.toContain("dynamic text"); });
  it("context appends dynamic tail, updates log state, and avoids duplicates", async () => { registerPromptProvider({ id: "p", getFragments: () => [frag("d", "dynamic", "dynamic text")] }); const pi = mockPi(); await load(pi); const r = await pi.hooks.get("context")!({ messages: [{ role: "user", content: [{ type: "text", text: "hi" }] }] }, { cwd: dir }); expect(r.messages).toHaveLength(2); expect(JSON.stringify(r.messages[1])).toContain("Dynamic turn context"); expect(pi.events.emit).not.toHaveBeenCalledWith("cache-friendly-prompt:dynamic-tail-rendered", expect.anything()); const r2 = await pi.hooks.get("context")!({ messages: r.messages }, { cwd: dir }); expect(r2.messages).toHaveLength(2); });
  it("context truncates very large dynamic tails", async () => { registerPromptProvider({ id: "p", getFragments: () => [frag("d", "dynamic", "x".repeat(20_000))] }); const pi = mockPi(); await load(pi); const r = await pi.hooks.get("context")!({ messages: [] }, { cwd: dir }); const text = r.messages[0].content[0].text; expect(text.length).toBeLessThan(13_000); expect(text).toContain("cache-friendly-prompt: omitted"); });
  it("context does not change messages when dynamic is empty", async () => { const pi = mockPi(); await load(pi); const messages = [{ role: "user", content: [] }]; const r = await pi.hooks.get("context")!({ messages }, { cwd: dir }); expect(r.messages).toBe(messages); });
  it("before_provider_request returns undefined, emits sent dynamic ids, and logs metadata only", async () => { registerPromptProvider({ id: "p", getFragments: () => [frag("s", "stable", "stable text"), frag("d", "dynamic", "dynamic text")] }); const pi = mockPi(); await load(pi); await pi.hooks.get("before_agent_start")!({ systemPrompt: "BASE SECRET" }, { cwd: dir, model: { provider: "prov", id: "model" } }); await pi.hooks.get("context")!({ messages: [] }, { cwd: dir, model: { provider: "prov", id: "model" } }); const ret = await pi.hooks.get("before_provider_request")!({ payload: { messages: [{ content: "USER FULL PROMPT <!-- fragment:test:d:coding_guidelines:dynamic:v1 -->" }] } }, { cwd: dir, model: { provider: "prov", id: "model" }, ui: { notify: vi.fn() } }); expect(ret).toBeUndefined(); expect(pi.events.emit).toHaveBeenCalledWith("cache-friendly-prompt:dynamic-tail-sent", { fragmentIds: ["d"] }); const log = fs.readFileSync(path.join(dir, ".pi-cache-friendly", "requests.jsonl"), "utf8"); expect(log).toContain("stablePrefixHash"); expect(log).toContain('"id":"d"'); expect(log).not.toContain("USER FULL PROMPT"); expect(log).not.toContain("BASE SECRET"); });
  it("before_provider_request logs injected stable snapshot instead of recollected stable fragments", async () => { let calls = 0; registerPromptProvider({ id: "p", getFragments: () => { calls++; return [frag("s", "stable", calls === 1 ? "stable one" : "stable two"), frag("d", "dynamic", `dynamic ${calls}`)]; } }); const pi = mockPi(); await load(pi); await pi.hooks.get("before_agent_start")!({ systemPrompt: "BASE" }, { cwd: dir }); await pi.hooks.get("context")!({ messages: [] }, { cwd: dir }); await pi.hooks.get("before_provider_request")!({ payload: { messages: [{ content: "<!-- fragment:test:d:coding_guidelines:dynamic:v1 -->" }] } }, { cwd: dir }); const log = JSON.parse(fs.readFileSync(path.join(dir, ".pi-cache-friendly", "requests.jsonl"), "utf8")); const expectedStableHash = hashFragment(renderPromptFragments([frag("s", "stable", "stable one")]).stableFragments[0]).hash; expect(log.injectedStableFragmentHashes).toEqual([expect.objectContaining({ id: "s", hash: expectedStableHash })]); expect(log.latestDynamicFragmentHashes).toEqual([expect.objectContaining({ id: "d" })]); expect(log.fragmentHashes).toContainEqual(expect.objectContaining({ id: "s", hash: expectedStableHash })); });
  it("warning notifications are off by default", async () => { const notify = vi.fn(); const pi = mockPi(); await load(pi); await pi.hooks.get("before_provider_request")!({ payload: { system: "Tokens used: 1\n<!-- prompt-fragments:Stable extension instructions -->" } }, { cwd: dir, ui: { notify } }); expect(notify).not.toHaveBeenCalled(); });
  it("warns when dynamic context appears in cacheable provider payload fields", async () => { const pi = mockPi(); await load(pi, { reportMode: "immediate" }); await pi.hooks.get("before_provider_request")!({ payload: { system: "<!-- prompt-fragments:Dynamic turn context -->\nvolatile" } }, { cwd: dir }); const log = JSON.parse(fs.readFileSync(path.join(dir, ".pi-cache-friendly", "requests.jsonl"), "utf8")); expect(log.warnings).toContainEqual(expect.objectContaining({ severity: "error", code: "DYNAMIC_CONTEXT_IN_CACHEABLE_PREFIX" })); });
  it("evaluates short-prefix warning against the effective base prompt and logs provider ids", async () => { registerPromptProvider({ id: "p", getFragments: () => [frag("s", "stable", "stable text")] }); const pi = mockPi(); await load(pi); await pi.hooks.get("before_agent_start")!({ systemPrompt: "BASE ".repeat(1100) }, { cwd: dir }); await pi.hooks.get("before_provider_request")!({ payload: { system: "sent" } }, { cwd: dir }); const log = JSON.parse(fs.readFileSync(path.join(dir, ".pi-cache-friendly", "requests.jsonl"), "utf8")); expect(log.promptProviderIds).toEqual(["p"]); expect(log.fragmentHashes.map((f: any) => f.id)).toContain("s"); expect(log.warnings.map((w: any) => w.code)).not.toContain("SHORT_STABLE_PREFIX"); });
  it("message_end writes actual usage log, summary fields, and report section", async () => { const pi = mockPi(); await load(pi, { reportMode: "immediate" }); await pi.hooks.get("before_agent_start")!({ systemPrompt: "BASE" }, { cwd: dir, model: { provider: "openai", id: "gpt" } }); await pi.hooks.get("message_end")!({ message: { role: "assistant", timestamp: 1_700_000_000_000, usage: { prompt_tokens: 2000, completion_tokens: 100, prompt_tokens_details: { cached_tokens: 1024 } } } }, { cwd: dir, model: { provider: "openai", id: "gpt" } }); const actual = JSON.parse(fs.readFileSync(path.join(dir, ".pi-cache-friendly", "actual-usage.jsonl"), "utf8")); expect(actual).toEqual(expect.objectContaining({ timestamp: "2023-11-14T22:13:20.000Z", inputTotalTokens: 2000, outputTokens: 100, cacheReadTokens: 1024, tokenHitRate: 0.512, usageSource: "provider_raw_usage" })); const summary = JSON.parse(fs.readFileSync(path.join(dir, ".pi-cache-friendly", "summary.json"), "utf8")); expect(summary.actualRequestCount).toBe(1); expect(summary.actualTokenHitRateWeighted).toBe(0.512); expect(summary.actualCacheableReadRateWeighted).toBeNull(); expect(summary.actualByProvider.openai.weightedTokenHitRate).toBe(0.512); expect(summary.actualByProviderModel["openai/gpt"].cacheReadTokens).toBe(1024); expect(summary.actualByRequestRole.main.weightedTokenHitRate).toBe(0.512); expect(summary.actualByProviderPrefixHash).toBeDefined(); expect(summary.actualByBaseSystemHash).toBeDefined(); expect(actual.correlationConfidence).toBe("runKey_latest"); expect(summary.actualColdRequestCount).toBe(1); expect(summary.actualWarmRequestCount).toBe(0); const report = fs.readFileSync(path.join(dir, ".pi-cache-friendly", "report.md"), "utf8"); expect(report).toContain("Actual provider cache hit rate"); expect(report).toContain("By provider/model"); expect(fs.existsSync(path.join(dir, ".pi-cache-friendly", "actual-hit-rate.svg"))).toBe(true); });
  it("message_end ignores non-assistant or usage-less messages but records zero cache reads", async () => { const pi = mockPi(); await load(pi); await pi.hooks.get("message_end")!({ message: { role: "user", usage: { input: 10, output: 1 } } }, { cwd: dir }); await pi.hooks.get("message_end")!({ message: { role: "assistant" } }, { cwd: dir }); expect(fs.existsSync(path.join(dir, ".pi-cache-friendly", "actual-usage.jsonl"))).toBe(false); await pi.hooks.get("message_end")!({ message: { role: "assistant", usage: { input: 10, output: 1, cacheRead: 0 } } }, { cwd: dir }); const actual = JSON.parse(fs.readFileSync(path.join(dir, ".pi-cache-friendly", "actual-usage.jsonl"), "utf8")); expect(actual.cacheReadTokens).toBe(0); expect(actual.tokenHitRate).toBe(0); });
  it("message_end deduplicates repeated actual usage events", async () => { const pi = mockPi(); await load(pi); const event = { message: { role: "assistant", id: "m1", timestamp: "2024-01-01T00:00:00.000Z", usage: { input: 10, output: 1, cacheRead: 5 } } }; await pi.hooks.get("message_end")!(event, { cwd: dir }); await pi.hooks.get("message_end")!(event, { cwd: dir }); const lines = fs.readFileSync(path.join(dir, ".pi-cache-friendly", "actual-usage.jsonl"), "utf8").trim().split(/\n/); expect(lines).toHaveLength(1); });
  it("message_end does not dedupe actual usage events without request/message id or timestamp", async () => { const pi = mockPi(); await load(pi); const event = { message: { role: "assistant", usage: { input: 10, output: 1, cacheRead: 5 } } }; await pi.hooks.get("message_end")!(event, { cwd: dir }); await pi.hooks.get("message_end")!(event, { cwd: dir }); const lines = fs.readFileSync(path.join(dir, ".pi-cache-friendly", "actual-usage.jsonl"), "utf8").trim().split(/\n/); expect(lines).toHaveLength(2); });
  it("message_end does not write actual usage when logRequests is false", async () => { const pi = mockPi(); await load(pi, { logRequests: false }); await pi.hooks.get("message_end")!({ message: { role: "assistant", usage: { input: 10, output: 1, cacheRead: 5 } } }, { cwd: dir }); expect(fs.existsSync(path.join(dir, ".pi-cache-friendly", "actual-usage.jsonl"))).toBe(false); });
  it("message_end treats numeric timestamps below millisecond epoch range as seconds", async () => { const pi = mockPi(); await load(pi); await pi.hooks.get("message_end")!({ message: { role: "assistant", timestamp: 1_700_000_000, usage: { input: 10, output: 1, cacheRead: 5 } } }, { cwd: dir }); const actual = JSON.parse(fs.readFileSync(path.join(dir, ".pi-cache-friendly", "actual-usage.jsonl"), "utf8")); expect(actual.timestamp).toBe("2023-11-14T22:13:20.000Z"); });
});
