import { describe, expect, it } from "vitest";

import {
	buildIssueSessionInitialMessage,
	buildIssueSessionSystemPrompt,
	READY_FOR_HUMAN_LABEL,
} from "./prompts.js";

describe("buildIssueSessionInitialMessage", () => {
	it("returns the implementation kick-off message by default (backward compatible)", () => {
		expect(buildIssueSessionInitialMessage(42)).toBe("issue-42に対応してください");
	});

	it("returns the implementation message for a ready-for-agent issue", () => {
		expect(buildIssueSessionInitialMessage(42, ["ready-for-agent"])).toBe(
			"issue-42に対応してください",
		);
	});

	it("returns the Agreement-phase message for a ready-for-human issue", () => {
		const message = buildIssueSessionInitialMessage(42, [READY_FOR_HUMAN_LABEL]);
		expect(message).toContain("issue-42");
		expect(message).toContain("合意形成");
		expect(message).toContain("ready-for-agent状態にします");
		// Must NOT auto-kick implementation.
		expect(message).not.toContain("に対応してください");
	});
});

describe("buildIssueSessionSystemPrompt", () => {
	it("returns the implementation-phase prompt by default (backward compatible)", () => {
		const prompt = buildIssueSessionSystemPrompt(42);
		expect(prompt).toContain("#42");
		expect(prompt).toContain("Phase 1");
		expect(prompt).toContain("review_fixer");
		expect(prompt).toContain("create_pr");
		// No Agreement-phase content leaks into the implementation path.
		expect(prompt).not.toContain("Agreement phase");
		expect(prompt).not.toContain("promote_to_ready_for_agent");
	});

	it("instructs the agent to demote and stop instead of opening a PR when blocked by ambiguity", () => {
		const prompt = buildIssueSessionSystemPrompt(42);

		expect(prompt).toContain("F3");
		expect(prompt).toContain("demote_to_ready_for_human");
		expect(prompt).toContain("ready-for-agent");
		expect(prompt).toContain("ready-for-human");
		expect(prompt).toContain("Do not commit, push, or create a PR");
		expect(prompt).toContain("issue_comment");
		expect(prompt.indexOf("demote_to_ready_for_human")).toBeLessThan(
			prompt.indexOf("issue_workflow `issue_comment`"),
		);
		expect(prompt).toContain("## Triage Notes");
		expect(prompt).toContain("What we've established so far");
		expect(prompt).toContain("判断を仰ぎたいこと");
		expect(prompt).toContain("> *This was generated by AI during triage.*");
		expect(prompt).toMatch(/leave|preserve/i);
		expect(prompt).toMatch(/previous agreement/i);
		expect(prompt).toMatch(/stop|halt/i);
	});

	it("returns the implementation-phase prompt for a ready-for-agent issue", () => {
		const prompt = buildIssueSessionSystemPrompt(42, ["ready-for-agent"]);
		expect(prompt).toContain("Phase 1");
		expect(prompt).not.toContain("Agreement phase");
	});

	it("prepends the Agreement-phase preamble for a ready-for-human issue", () => {
		const prompt = buildIssueSessionSystemPrompt(42, [READY_FOR_HUMAN_LABEL]);

		// Agreement phase is introduced and references the triggering label.
		expect(prompt).toContain("Agreement phase");
		expect(prompt).toContain(READY_FOR_HUMAN_LABEL);

		// The human must express agreement before the agent proceeds (soft constraint).
		expect(prompt).toMatch(/express explicit agreement|Wait for the human/i);

		// Hand-off step 1: triage-notes comment via issue_comment.
		expect(prompt).toContain("issue_comment");
		expect(prompt).toContain("## Triage Notes");
		expect(prompt).toContain("established so far");
		expect(prompt).toContain("判断を仰ぎたいこと");
		expect(prompt).toContain("> *This was generated by AI during triage.*");

		// Hand-off step 2: label switch via the #111 action, not raw gh.
		expect(prompt).toContain("promote_to_ready_for_agent");
		expect(prompt).toContain("ready-for-human");
		expect(prompt).toContain("ready-for-agent");
		expect(prompt.toLowerCase()).toContain("do not call `gh`");

		// Hand-off step 3: same-session continuation into implementation.
		expect(prompt).toContain("same session");

		// The implementation-phase workflow is still present (continuous hand-off).
		expect(prompt).toContain("Phase 1");
		expect(prompt).toContain("review_fixer");
	});
});
