/**
 * issue/prompts.ts — session prompts shared by the launcher (cli.ts) and the
 * orchestration continuation hook (orchestration/extension.ts).
 *
 * Extracted to avoid a circular import between cli.ts (which imports the
 * orchestration modules) and orchestration/extension.ts (which needs the same
 * prompt builders to start a Work Pi).
 */

/** Triage label that starts a session in the Agreement phase (ADR-0025 slice E). */
export const READY_FOR_HUMAN_LABEL = "ready-for-human";

function buildTriageNotesExample(openQuestionsExample = "- question 1"): string {
	return [
		"```",
		"## Triage Notes",
		"",
		"**What we've established so far:**",
		"",
		"- agreed point 1",
		"- agreed point 2",
		"",
		"**Open questions / things to confirm (判断を仰ぎたいこと):**",
		"",
		openQuestionsExample,
		"",
		"> *This was generated by AI during triage.*",
		"```",
	].join("\n");
}

/**
 * Implementation-phase workflow instructions (Phase 1–3 self-run). Shared by
 * the normal `ready-for-agent` path and appended after the Agreement-phase
 * preamble when a session starts from `ready-for-human`.
 */
function buildImplementationPhasePrompt(issueNumber: number): string {
	const f3TriageNotesBlock = buildTriageNotesExample(
		"- the specific new decision needed before implementation can continue",
	);

	return [
		`You are working in an issue worktree for GitHub issue #${issueNumber}.`,
		"Follow this issue workflow in explicit phases when the user asks you to implement or fix the issue:",
		"F3 stuck/blocked handling: if you get stuck because a missing product decision, unclear spec, edge case, or gap in the brief is necessary for a quality implementation, do not guess and do not produce an untrusted work product. Do not commit, push, or create a PR; leave/preserve the partially implemented worktree exactly as-is so it can be resumed later.",
		`When F3 happens, first use issue_workflow \`demote_to_ready_for_human\` (issue #${issueNumber}) to switch \`ready-for-agent\` → \`ready-for-human\`.`,
		`Then post an issue comment via issue_workflow \`issue_comment\` (issue #${issueNumber}) using this triage-notes structure, summarising established facts and only the new decision(s) needed:`,
		f3TriageNotesBlock,
		"After the demotion and comment are done, stop/halt the Work Pi after reporting that the issue needs human input. Do not run review_fixer or Phase 3 after F3 demotion.",
		"If this session resumed from prior Agreement-phase comments, preserve the previous agreement as established context and ask only about the newly blocking question; do not restart consensus from zero.",
		"Phase 1 — issue対応: read the issue, confirm dependency status if needed, understand acceptance criteria, then implement/fix the issue in this session.",
		"Phase 2 — review_fixerによる調査と修正: immediately invoke the review_fixer tool yourself. Inspect its structured result, address any required follow-up, and rerun review_fixer if the result says the gate failed or the user asks for another pass.",
		"Phase 3 — issue_workflow (status → diff → commit → push → create_pr): only after review_fixer succeeds, use the issue_workflow tool to inspect status/diff, then commit, push the issue branch, and create the PR. Always go through issue_workflow; do NOT run git/gh via the bash tool (git-safety intercepts it and commit/PR messages get mangled by shell expansion).",
		"create_pr should produce a ready (non-draft) PR; review_fixer has already gated implementation quality.",
		"Do not collapse these phases. Announce the current phase briefly before acting so the user can follow progress.",
		"Do not merely recommend review_fixer after implementation; invoke it yourself unless the issue is blocked or the user explicitly forbids it.",
		"Do not run thermo-nuclear-code-quality-review directly in the parent Issue Pi as the normal gate; use review_fixer so the review happens in a clean child Pi context. Direct /skill force-load is only a fallback if review_fixer errors and explicitly tells you to use it.",
		"Do not commit, push, or create a PR before review_fixer has completed successfully.",
	].join("\n");
}

/**
 * Agreement-phase preamble prepended to the implementation-phase prompt when
 * the issue carries `ready-for-human` (ADR-0025 slice E).
 *
 * The human and the agent collaborate to lock down the spec; only when the
 * human expresses agreement does the agent switch the label
 * (`ready-for-human` → `ready-for-agent`) and continue into implementation
 * in the same session. The hand-off is a soft constraint driven by the human.
 */
function buildAgreementPhasePrompt(issueNumber: number): string {
	const triageNotesBlock = buildTriageNotesExample();

	return [
		`This issue carries the \`${READY_FOR_HUMAN_LABEL}\` label, so this session opens in the Agreement phase: collaborate with the human to lock down the spec before any implementation.`,
		"",
		"Agreement phase:",
		"- Read the issue body, then discuss scope and spec with the human. Ask specific, actionable clarifying questions where the spec is ambiguous, and record what you agree on as you go.",
		'- Do NOT switch the label, post the agreement comment, or start implementing on your own initiative. Wait for the human to express explicit agreement (e.g. 「これでいく」, "let\'s go with that", "approved", "proceed").',
		"",
		"When the human agrees, perform all of these steps before coding:",
		`1. Post a Triage Notes comment via issue_workflow \`issue_comment\` (issue #${issueNumber}) summarising the agreement, using this structure:`,
		triageNotesBlock,
		`2. Switch the label \`ready-for-human\` → \`ready-for-agent\` via issue_workflow \`promote_to_ready_for_agent\` (issue #${issueNumber}). Do not call \`gh\` directly — go through issue_workflow so the gate and triage-state roles stay consistent.`,
		"3. Continue in this same session into the implementation phase below (Phase 1–3 self-run). Do not relaunch; just proceed.",
		"",
		"During the Agreement phase the Work Pi behaves like a normal Pi: the human closes the session, there is no auto-close and no timeout.",
	].join("\n");
}

/**
 * Build the system prompt for an issue Work Pi. When the issue carries the
 * `ready-for-human` label, the Agreement-phase preamble is prepended to the
 * standard implementation-phase instructions (ADR-0025 slice E).
 */
export function buildIssueSessionSystemPrompt(issueNumber: number, labels: string[] = []): string {
	const implementation = buildImplementationPhasePrompt(issueNumber);
	if (labels.includes(READY_FOR_HUMAN_LABEL)) {
		return `${buildAgreementPhasePrompt(issueNumber)}\n\n${implementation}`;
	}
	return implementation;
}

/**
 * Build the initial user message for an issue Work Pi. It branches on the
 * issue's label so a `ready-for-human` issue opens in the Agreement phase
 * instead of auto-running implementation.
 */
export function buildIssueSessionInitialMessage(issueNumber: number, labels: string[] = []): string {
	if (labels.includes(READY_FOR_HUMAN_LABEL)) {
		return `issue-${issueNumber}に対応するために人間との合意形成を行い、agentが実装できるように落とし込み、ready-for-agent状態にします`;
	}
	return `issue-${issueNumber}に対応してください`;
}
