import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import { clearPromptProvidersForTests, registerPromptProvider } from "../prompt-core/index.js";
vi.mock("@earendil-works/pi-coding-agent", () => ({}));
function mockPi() { const hooks = new Map<string, Function>(); return { hooks, events: { emit: vi.fn() }, on: vi.fn((e: string, h: Function) => hooks.set(e, h)) }; }
const frag = (id: string, stability: any, content: string) => ({ id, source: "test", kind: "coding_guidelines" as const, stability, scope: "global" as const, priority: 1, version: "v1", content });
describe("cache-friendly-prompt", () => {
  let dir: string;
  beforeEach(() => { clearPromptProvidersForTests(); dir = fs.mkdtempSync(path.join(os.tmpdir(), "cfp-")); });
  afterEach(() => clearPromptProvidersForTests());
  async function load(pi: any, config?: any) { const { default: ext } = await import("./index.js"); ext(pi, config); }
  it("registers hooks", async () => { const pi = mockPi(); await load(pi); expect([...pi.hooks.keys()]).toEqual(["before_agent_start", "context", "before_provider_request"]); });
  it("before_agent_start appends stable then semi-stable but not dynamic", async () => { registerPromptProvider({ id: "p", getFragments: () => [frag("s", "stable", "stable text"), frag("m", "semi_stable", "semi text"), frag("d", "dynamic", "dynamic text")] }); const pi = mockPi(); await load(pi); const r = await pi.hooks.get("before_agent_start")!({ systemPrompt: "BASE" }, { cwd: dir, model: { provider: "p", id: "m" } }); expect(r.systemPrompt).toMatch(/^BASE/); expect(r.systemPrompt.indexOf("stable text")).toBeLessThan(r.systemPrompt.indexOf("semi text")); expect(r.systemPrompt).not.toContain("dynamic text"); });
  it("context appends dynamic tail, updates log state, and avoids duplicates", async () => { registerPromptProvider({ id: "p", getFragments: () => [frag("d", "dynamic", "dynamic text")] }); const pi = mockPi(); await load(pi); const r = await pi.hooks.get("context")!({ messages: [{ role: "user", content: [{ type: "text", text: "hi" }] }] }, { cwd: dir }); expect(r.messages).toHaveLength(2); expect(JSON.stringify(r.messages[1])).toContain("Dynamic turn context"); expect(pi.events.emit).not.toHaveBeenCalledWith("cache-friendly-prompt:dynamic-tail-rendered", expect.anything()); const r2 = await pi.hooks.get("context")!({ messages: r.messages }, { cwd: dir }); expect(r2.messages).toHaveLength(2); });
  it("context does not change messages when dynamic is empty", async () => { const pi = mockPi(); await load(pi); const messages = [{ role: "user", content: [] }]; const r = await pi.hooks.get("context")!({ messages }, { cwd: dir }); expect(r.messages).toBe(messages); });
  it("before_provider_request returns undefined, emits sent dynamic ids, and logs metadata only", async () => { registerPromptProvider({ id: "p", getFragments: () => [frag("s", "stable", "stable text"), frag("d", "dynamic", "dynamic text")] }); const pi = mockPi(); await load(pi); await pi.hooks.get("before_agent_start")!({ systemPrompt: "BASE SECRET" }, { cwd: dir, model: { provider: "prov", id: "model" } }); await pi.hooks.get("context")!({ messages: [] }, { cwd: dir, model: { provider: "prov", id: "model" } }); const ret = await pi.hooks.get("before_provider_request")!({ payload: { messages: [{ content: "USER FULL PROMPT <!-- fragment:test:d:coding_guidelines:dynamic:v1 -->" }] } }, { cwd: dir, model: { provider: "prov", id: "model" }, ui: { notify: vi.fn() } }); expect(ret).toBeUndefined(); expect(pi.events.emit).toHaveBeenCalledWith("cache-friendly-prompt:dynamic-tail-sent", { fragmentIds: ["d"] }); const log = fs.readFileSync(path.join(dir, ".pi-cache-friendly", "requests.jsonl"), "utf8"); expect(log).toContain("stablePrefixHash"); expect(log).toContain('"id":"d"'); expect(log).not.toContain("USER FULL PROMPT"); expect(log).not.toContain("BASE SECRET"); });
  it("warning notifications are off by default", async () => { const notify = vi.fn(); const pi = mockPi(); await load(pi); await pi.hooks.get("before_provider_request")!({ payload: { system: "Tokens used: 1\n<!-- prompt-fragments:Stable extension instructions -->" } }, { cwd: dir, ui: { notify } }); expect(notify).not.toHaveBeenCalled(); });
});
